### ISSUE TITLE
Дизайн на страница с публикации

### ISSUE THREAD

**Issue by viksuper555** [viksuper555/DoctorSystem#12]
Разработка на фронтенда на страницата с публикации. Може да се използва [boostrap](https://getbootstrap.com/).
Представям си го като news feed на фейсбук или instagram.
В началото се създават 2-3 "фалшиви" поста, за да може самият дизайн да се разработва независимо от бекенда.

**Comment by dbozova** [comment]
![Image](https://user-images.githubusercontent.com/93641438/204640708-a3429c22-8ebd-4cf4-bbc6-206cb056ccd1.png)
