### ISSUE TITLE
Дизайн на начална страница + Navigation Bar

### ISSUE THREAD

**Issue by viksuper555** [viksuper555/DoctorSystem#7]
- Избор на цветова гама - може да се ползва [Coolors.io](https://coolors.co/)
- Избор на дизайн на Navigation Bar (Меню отгоре) - може да се използва [Bootstrap](https://getbootstrap.com/). Ето още [примери](https://colorlib.com/wp/bootstrap-navbar/) - перфектни, като се взаимстват със снимка ([пример](https://cdn.pixabay.com/photo/2021/11/23/18/11/pharmacy-6819335_960_720.png))
- Избор на съдържание на началната страница. Може да показва информация за потребителя, бързи връзки с нещо полезно и новини.

**Comment by viksuper555** [comment]
https://coolors.co/palette/114b5f-1a936f-88d498-c6dabf-f3e9d2'

**Comment by viksuper555** [comment]
![Image](https://user-images.githubusercontent.com/15073936/203164144-af9dd073-3383-49c8-a016-e4bbe742d7f3.png)

**Comment by dbozova** [comment]
![Image](https://user-images.githubusercontent.com/93641438/203164834-0d644584-1817-4645-965e-2ef2888344af.png)
